### ISSUE TITLE
DataGrip2022.1.1安装插件报错

### ISSUE THREAD

**Issue by nygula** [nancheung97/legado-reader#2]
DataGrip2022.1.1安装插件报错
`com.intellij.diagnostic.PluginException: Cannot create class com.nancheung.plugins.jetbrains.legadoreader.gui.IndexWindowFactory (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Legado Reader, id=com.nancheung.plugins.jetbrains.legado-reader, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\DataGrip2022.1\plugins\legado-reader-1.0-SNAPSHOT.jar, version=1.0-SNAPSHOT, package=null, isBundled=false), packagePrefix=null, instanceId=20, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:884)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:901)
	at com.intellij.openapi.wm.ToolWindowEP.getToolWindowFactory(ToolWindowEP.java:113)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:461)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$registerEpListeners$1.extensionAdded(ToolWindowSetInitializer.kt:233)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$registerEpListeners$1.extensionAdded(ToolWindowSetInitializer.kt:231)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.notifyListeners(ExtensionPointImpl.java:765)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$registerExtensions$18(ExtensionPointImpl.java:969)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugin$2.run(DynamicPlugins.kt:843)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1015)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:829)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:809)
	at com.intellij.ide.plugins.PluginInstaller.installAndLoadDynamicPlugin(PluginInstaller.java:401)
	at com.intellij.ide.plugins.PluginInstaller.installAndLoadDynamicPlugin(PluginInstaller.java:378)
	at com.intellij.ide.plugins.PluginInstaller.installPluginFromCallbackData(PluginInstaller.java:465)
	at com.intellij.ide.plugins.PluginInstaller.installFromDisk(PluginInstaller.java:356)
	at com.intellij.ide.plugins.PluginInstaller.installFromDisk(PluginInstaller.java:225)
	at com.intellij.ide.plugins.PluginDropHandler.lambda$handleDrop$1(PluginDropHandler.java:38)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:715)
	at com.intellij.ide.plugins.PluginDropHandler.handleDrop(PluginDropHandler.java:38)
	at com.intellij.openapi.fileEditor.impl.text.FileDropHandler.lambda$handleDrop$0(FileDropHandler.java:48)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:724)
	at com.intellij.openapi.fileEditor.impl.text.FileDropHandler.handleDrop(FileDropHandler.java:47)
	at com.intellij.openapi.editor.EditorDropHandler.handleDrop(EditorDropHandler.java:15)
	at com.intellij.openapi.editor.impl.EditorImpl.handleDrop(EditorImpl.java:4774)
	at com.intellij.openapi.editor.impl.EditorImpl$MyTransferHandler.importData(EditorImpl.java:4843)
	at java.desktop/javax.swing.TransferHandler$DropHandler.drop(TransferHandler.java:1544)
	at java.desktop/java.awt.dnd.DropTarget.drop(DropTarget.java:452)
	at java.desktop/javax.swing.TransferHandler$SwingDropTarget.drop(TransferHandler.java:1282)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:547)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:863)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:787)
	at java.desktop/sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4894)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4621)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4483)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: cn/hutool/core/lang/TypeReference
	at com.nancheung.plugins.jetbrains.legadoreader.gui.IndexWindow.refreshBookshelf(IndexWindow.java:164)
	at com.nancheung.plugins.jetbrains.legadoreader.gui.IndexWindow.<init>(IndexWindow.java:106)
	at com.nancheung.plugins.jetbrains.legadoreader.gui.IndexWindowFactory.<init>(IndexWindowFactory.java:12)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:845)
	... 69 more
Caused by: java.lang.ClassNotFoundException: cn.hutool.core.lang.TypeReference PluginClassLoader(plugin=PluginDescriptor(name=Legado Reader, id=com.nancheung.plugins.jetbrains.legado-reader, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\DataGrip2022.1\plugins\legado-reader-1.0-SNAPSHOT.jar, version=1.0-SNAPSHOT, package=null, isBundled=false), packagePrefix=null, instanceId=20, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 73 more
`

**Comment by nancheung97** [comment]
我使用2022.1.5可用，jar包我已重新更新过一次，是否是使用的最新jar包呢
![image](https://user-images.githubusercontent.com/34061813/216282365-d518655f-ec01-432c-b7d5-05d0efef41b4.png)

**Comment by nancheung97** [comment]
![image](https://user-images.githubusercontent.com/34061813/216285547-9313d0c6-9329-43a0-b9d9-e3b387e9963a.png)
使用2022.1.1版本也能正常使用，你试试这个包
https://github.com/nancheung97/legado-reader/releases/download/v1.0/legado-reader-1.0.1-SNAPSHOT.zip

**Comment by nancheung97** [comment]
先关闭了，如果还有问题可以继续反馈
